language: ruby

cache: bundler

rvm:
  - 2.0.0-p247
  - 2.2.0
  - jruby-19mode

env:
  - NSQ_DOWNLOAD=nsq-0.3.2.linux-amd64.go1.4.1

script:
  - wget http://bitly-downloads.s3.amazonaws.com/nsq/$NSQ_DOWNLOAD.tar.gz
  - tar zxvf $NSQ_DOWNLOAD.tar.gz
  - export PATH=$NSQ_DOWNLOAD/bin:$PATH
  - pushd $TRAVIS_BUILD_DIR
  - bundle exec rake spec
  - popd

notifications:
  email: true

sudo: false