language: ruby

cache: bundler

rvm:
  - 2.0.0-p598
  - 2.2.0
  - jruby-19mode
  - jruby-head

env:
  global:
    - NSQ_DOWNLOAD=nsq-0.3.6.linux-amd64.go1.5.1
    - JRUBY_OPTS="--server -J-Dfile.encoding=utf8 --2.0"
    - FOCUS=false
    - FULL=true
    - DEBUG=true

install:
  - wget http://bitly-downloads.s3.amazonaws.com/nsq/$NSQ_DOWNLOAD.tar.gz
  - tar zxvf $NSQ_DOWNLOAD.tar.gz
  - export PATH=$NSQ_DOWNLOAD/bin:$PATH
  - bundle install --jobs=3 --retry=3

script:
  - bundle exec rake spec

notifications:
  email:
    recipients:
      - aemadrid@gmail.com
    on_success: change
    on_failure: change

sudo: false